"""
Script to update Kaggle_Cloud_Engine.ipynb with Dual T4 GPU support (cuda:0 & cuda:1)
and patch Wav2Lip/face_detection/api.py for PyTorch / Python 3.12 torch.device type safety.
"""
import os
import json

notebook_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "Kaggle_Cloud_Engine.ipynb"))

if not os.path.exists(notebook_path):
    print(f"❌ Notebook not found at: {notebook_path}")
    exit(1)

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

cell_2_code = [
    "# ============================================================\n",
    "# CELL 2 — DUAL T4 GPU LIPSYNC SERVER (Run AFTER Cell 1 finishes)\n",
    "# ============================================================\n",
    "import os, sys, base64, subprocess, traceback, threading, queue\n",
    "import torch\n",
    "from flask import Flask, request, jsonify\n",
    "from PIL import Image\n",
    "\n",
    "# ╔══════════════════════════════════════════════════════════╗\n",
    "# ║  👉 PASTE YOUR NGROK TOKEN BELOW                        ║\n",
    "# ╚══════════════════════════════════════════════════════════╝\n",
    "NGROK_TOKEN = \"3BZaGFS85TRNgCpNbFcjoTR0V5P_7KPvvJ52uQrtESVeEXAg9\"\n",
    "\n",
    "# ── Configuration ──\n",
    "JOBS_DIR = \"/kaggle/working/lipsync_jobs\"\n",
    "WAV2LIP_DIR = \"/kaggle/working/Wav2Lip\"\n",
    "CHECKPOINT = os.path.join(WAV2LIP_DIR, \"checkpoints\", \"wav2lip_gan.pth\")\n",
    "\n",
    "os.makedirs(JOBS_DIR, exist_ok=True)\n",
    "os.makedirs(os.path.join(WAV2LIP_DIR, \"temp\"), exist_ok=True)\n",
    "\n",
    "# Verify setup\n",
    "assert os.path.exists(os.path.join(WAV2LIP_DIR, \"inference.py\")), \\\n",
    "    \"❌ Wav2Lip/inference.py NOT FOUND! Run Cell 1 first!\"\n",
    "assert os.path.exists(CHECKPOINT), \\\n",
    "    \"❌ Checkpoint NOT FOUND! Run Cell 1 first!\"\n",
    "print(\"✅ Wav2Lip verified\")\n",
    "\n",
    "# ── Multi-GPU Worker Pool Setup (T4 x 2) ──\n",
    "gpu_queue = queue.Queue()\n",
    "num_gpus = torch.cuda.device_count()\n",
    "if num_gpus >= 2:\n",
    "    gpu_queue.put(\"cuda:0\")\n",
    "    gpu_queue.put(\"cuda:1\")\n",
    "    print(f\"🚀 DUAL GPU MODE ACTIVATED: 2x T4 GPUs ({torch.cuda.get_device_name(0)} & {torch.cuda.get_device_name(1)})\")\n",
    "elif num_gpus == 1:\n",
    "    gpu_queue.put(\"cuda:0\")\n",
    "    print(f\"⚡ SINGLE GPU MODE: {torch.cuda.get_device_name(0)}\")\n",
    "else:\n",
    "    gpu_queue.put(\"cpu\")\n",
    "    print(\"⚠️ CPU MODE: No CUDA GPUs detected\")\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "def prepare_avatar(src, dst, size=720):\n",
    "    \"\"\"Resize avatar to square for Wav2Lip face detection.\"\"\"\n",
    "    img = Image.open(src).convert(\"RGB\")\n",
    "    w, h = img.size\n",
    "    scale = min(size/w, size/h)\n",
    "    nw, nh = int(w*scale), int(h*scale)\n",
    "    img = img.resize((nw, nh), Image.LANCZOS)\n",
    "    canvas = Image.new(\"RGB\", (size, size), (0,0,0))\n",
    "    canvas.paste(img, ((size-nw)//2, (size-nh)//2))\n",
    "    canvas.save(dst, \"PNG\")\n",
    "    print(f\"  🖼️ Avatar: {w}x{h} → {size}x{size}\")\n",
    "\n",
    "import sys\n",
    "sys.path.append(WAV2LIP_DIR)\n",
    "\n",
    "print(\"\\n🔧 Patching face_detection/api.py...\")\n",
    "# Patch face_detection/api.py to prevent TypeError on torch.device iteration\n",
    "api_path = os.path.join(WAV2LIP_DIR, \"face_detection\", \"api.py\")\n",
    "if os.path.exists(api_path):\n",
    "    with open(api_path, \"r\") as f: api_code = f.read()\n",
    "    if \"if 'cuda' in device:\" in api_code:\n",
    "        api_code = api_code.replace(\"if 'cuda' in device:\", \"if 'cuda' in str(device):\")\n",
    "        with open(api_path, \"w\") as f: f.write(api_code)\n",
    "        print(\"  ✅ Patched face_detection/api.py for torch.device string matching.\")\n",
    "\n",
    "def run_wav2lip(scene_id, audio_path, avatar_path, output_mp4, target_device=\"cuda:0\"):\n",
    "    \"\"\"Run Wav2Lip inference on assigned GPU device with process isolation.\"\"\"\n",
    "    temp_dir = os.path.join(WAV2LIP_DIR, \"temp\")\n",
    "    for f in os.listdir(temp_dir):\n",
    "        try: os.remove(os.path.join(temp_dir, f))\n",
    "        except: pass\n",
    "    \n",
    "    prep = os.path.join(JOBS_DIR, f\"{scene_id}_prep.png\")\n",
    "    prepare_avatar(avatar_path, prep)\n",
    "    \n",
    "    print(f\"  🚀 Running Wav2Lip on {target_device} for {scene_id}...\")\n",
    "    dev_str = str(target_device)\n",
    "    gpu_id = str(dev_str.split(\":\")[-1]) if \":\" in dev_str else \"0\"\n",
    "    \n",
    "    env = os.environ.copy()\n",
    "    if torch.cuda.is_available() and \":\" in dev_str:\n",
    "        env[\"CUDA_VISIBLE_DEVICES\"] = gpu_id\n",
    "    \n",
    "    cmd = [\n",
    "        sys.executable, \"inference.py\",\n",
    "        \"--checkpoint_path\", os.path.join(WAV2LIP_DIR, \"checkpoints\", \"wav2lip_gan.pth\"),\n",
    "        \"--face\", prep,\n",
    "        \"--audio\", audio_path,\n",
    "        \"--outfile\", output_mp4,\n",
    "        \"--pads\", \"0\", \"10\", \"0\", \"0\",\n",
    "        \"--resize_factor\", \"1\",\n",
    "        \"--nosmooth\",\n",
    "        \"--fps\", \"25.0\",\n",
    "        \"--face_det_batch_size\", \"64\",\n",
    "        \"--wav2lip_batch_size\", \"128\"\n",
    "    ]\n",
    "    \n",
    "    try:\n",
    "        res = subprocess.run(\n",
    "            cmd,\n",
    "            cwd=WAV2LIP_DIR,\n",
    "            env=env,\n",
    "            stdout=subprocess.PIPE,\n",
    "            stderr=subprocess.STDOUT,\n",
    "            text=True\n",
    "        )\n",
    "        if res.returncode != 0:\n",
    "            print(f\"  ❌ Inference Exception on {target_device} (code {res.returncode}):\\n{res.stdout}\")\n",
    "            return False\n",
    "        else:\n",
    "            for line in res.stdout.splitlines():\n",
    "                if \"100%\" in line or \"Load checkpoint\" in line or \"Model loaded\" in line or \"ffmpeg\" in line:\n",
    "                    print(f\"    {line}\")\n",
    "    except Exception as e:\n",
    "        print(f\"  ❌ Inference Exception on {target_device}: {e}\")\n",
    "        traceback.print_exc()\n",
    "        return False\n",
    "    \n",
    "    if os.path.exists(output_mp4) and os.path.getsize(output_mp4) > 1000:\n",
    "        print(f\"  ✅ Video completed on {target_device}: {os.path.getsize(output_mp4)} bytes\")\n",
    "        return True\n",
    "    \n",
    "    return False\n",
    "\n",
    "\n",
    "@app.route(\"/health\")\n",
    "def health():\n",
    "    gpus = [torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())] if torch.cuda.is_available() else [\"CPU\"]\n",
    "    return jsonify({\"status\": \"online\", \"gpus\": gpus, \"gpu_count\": len(gpus)})\n",
    "\n",
    "@app.route(\"/clear_cache\")\n",
    "def clear_cache():\n",
    "    import torch, gc\n",
    "    gc.collect()\n",
    "    if torch.cuda.is_available(): torch.cuda.empty_cache()\n",
    "    return jsonify({\"status\": \"cleared\"})\n",
    "\n",
    "@app.route(\"/generate_lipsync\", methods=[\"POST\"])\n",
    "def generate_lipsync():\n",
    "    try:\n",
    "        data = request.json\n",
    "        scene_id = data.get(\"scene_id\", \"scene_01\")\n",
    "        \n",
    "        # Save audio\n",
    "        audio_path = os.path.join(JOBS_DIR, f\"{scene_id}.wav\")\n",
    "        with open(audio_path, \"wb\") as f:\n",
    "            f.write(base64.b64decode(data[\"audio_base64\"]))\n",
    "        \n",
    "        # Save avatar\n",
    "        avatar_path = os.path.join(JOBS_DIR, f\"{scene_id}_avatar.png\")\n",
    "        with open(avatar_path, \"wb\") as f:\n",
    "            f.write(base64.b64decode(data[\"avatar_image_base64\"]))\n",
    "        \n",
    "        output_mp4 = os.path.join(JOBS_DIR, f\"{scene_id}_sync.mp4\")\n",
    "        \n",
    "        # Acquire available GPU device from queue (cuda:0 or cuda:1)\n",
    "        target_gpu = gpu_queue.get()\n",
    "        print(f\"🎬 {scene_id}: Acquired {target_gpu}\")\n",
    "        try:\n",
    "            ok = run_wav2lip(scene_id, audio_path, avatar_path, output_mp4, target_device=target_gpu)\n",
    "        finally:\n",
    "            gpu_queue.put(target_gpu)\n",
    "            print(f\"  🔓 Released {target_gpu}\")\n",
    "        \n",
    "        if not ok:\n",
    "            raise Exception(f\"Wav2Lip produced no output for {scene_id}\")\n",
    "        \n",
    "        with open(output_mp4, \"rb\") as f:\n",
    "            video_b64 = base64.b64encode(f.read()).decode()\n",
    "        \n",
    "        print(f\"  ✅ {scene_id} complete on {target_gpu}!\")\n",
    "        return jsonify({\"status\": \"success\", \"lipsync_video_base64\": video_b64})\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"🔥 Error: {traceback.format_exc()}\")\n",
    "        return jsonify({\"status\": \"error\", \"error_message\": str(e)}), 500\n",
    "\n",
    "# ── Start Server ──\n",
    "from pyngrok import ngrok\n",
    "\n",
    "try:\n",
    "    from kaggle_secrets import UserSecretsClient\n",
    "    token = UserSecretsClient().get_secret(\"NGROK_AUTH_TOKEN\") or NGROK_TOKEN\n",
    "except:\n",
    "    token = NGROK_TOKEN\n",
    "\n",
    "if not token or \"paste_your\" in token:\n",
    "    print(\"❌ Paste your ngrok token in NGROK_TOKEN variable!\")\n",
    "else:\n",
    "    ngrok.set_auth_token(token)\n",
    "    try:\n",
    "        for t in ngrok.get_tunnels(): ngrok.disconnect(t.public_url)\n",
    "    except: pass\n",
    "    tunnel = ngrok.connect(5000)\n",
    "    url = tunnel.public_url\n",
    "    if hasattr(tunnel, 'public_url'):\n",
    "        url = tunnel.public_url\n",
    "    else:\n",
    "        url = str(tunnel)\n",
    "    if 'https://' in url:\n",
    "        import re\n",
    "        match = re.search(r'(https://[^\\s\\\"]+\\.ngrok[^\\s\\\"]*)', url)\n",
    "        if match:\n",
    "            url = match.group(1)\n",
    "    print(f\"\\n🚀 PUBLIC URL: {url}\")\n",
    "    print(f\"\\n📋 Paste in backend/.env:\")\n",
    "    print(f\"   CLOUD_RENDER_URL={url}\")\n",
    "    app.run(host=\"0.0.0.0\", port=5000, threaded=True)"
]

if len(nb["cells"]) >= 2:
    nb["cells"][1]["source"] = cell_2_code
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    print(f"✅ Successfully patched Kaggle_Cloud_Engine.ipynb for 2x T4 GPUs at {notebook_path}")
else:
    print("❌ Cell 2 not found in notebook.")
